# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'param_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ParamWindow(object):
    def setupUi(self, ParamWindow):
        ParamWindow.setObjectName(_fromUtf8("ParamWindow"))
        ParamWindow.resize(564, 651)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        ParamWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(ParamWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_10 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_10.setContentsMargins(0, 3, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.DT_box = QtGui.QDateTimeEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.DT_box.sizePolicy().hasHeightForWidth())
        self.DT_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.DT_box.setFont(font)
        self.DT_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DT_box.setAutoFillBackground(False)
        self.DT_box.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.DT_box.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DT_box.setCalendarPopup(True)
        self.DT_box.setObjectName(_fromUtf8("DT_box"))
        self.verticalLayout.addWidget(self.DT_box)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.DT_read_b = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.DT_read_b.sizePolicy().hasHeightForWidth())
        self.DT_read_b.setSizePolicy(sizePolicy)
        self.DT_read_b.setMinimumSize(QtCore.QSize(90, 0))
        self.DT_read_b.setMaximumSize(QtCore.QSize(90, 16777215))
        self.DT_read_b.setObjectName(_fromUtf8("DT_read_b"))
        self.horizontalLayout.addWidget(self.DT_read_b)
        self.DT_set_b = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.DT_set_b.sizePolicy().hasHeightForWidth())
        self.DT_set_b.setSizePolicy(sizePolicy)
        self.DT_set_b.setMinimumSize(QtCore.QSize(90, 0))
        self.DT_set_b.setMaximumSize(QtCore.QSize(90, 16777215))
        self.DT_set_b.setObjectName(_fromUtf8("DT_set_b"))
        self.horizontalLayout.addWidget(self.DT_set_b)
        self.DT_set_now_b = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.DT_set_now_b.sizePolicy().hasHeightForWidth())
        self.DT_set_now_b.setSizePolicy(sizePolicy)
        self.DT_set_now_b.setMinimumSize(QtCore.QSize(90, 0))
        self.DT_set_now_b.setMaximumSize(QtCore.QSize(90, 16777215))
        self.DT_set_now_b.setObjectName(_fromUtf8("DT_set_now_b"))
        self.horizontalLayout.addWidget(self.DT_set_now_b)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.DT_set_res_t = QtGui.QPushButton(self.groupBox)
        self.DT_set_res_t.setText(_fromUtf8(""))
        self.DT_set_res_t.setFlat(True)
        self.DT_set_res_t.setObjectName(_fromUtf8("DT_set_res_t"))
        self.verticalLayout.addWidget(self.DT_set_res_t)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout()
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.label_37 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMinimumSize(QtCore.QSize(90, 0))
        self.label_37.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_51.addWidget(self.label_37)
        self.SA_box = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SA_box.sizePolicy().hasHeightForWidth())
        self.SA_box.setSizePolicy(sizePolicy)
        self.SA_box.setMinimumSize(QtCore.QSize(150, 0))
        self.SA_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.SA_box.setText(_fromUtf8(""))
        self.SA_box.setObjectName(_fromUtf8("SA_box"))
        self.horizontalLayout_51.addWidget(self.SA_box)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_54 = QtGui.QHBoxLayout()
        self.horizontalLayout_54.setObjectName(_fromUtf8("horizontalLayout_54"))
        self.label_38 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMinimumSize(QtCore.QSize(90, 0))
        self.label_38.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_54.addWidget(self.label_38)
        self.SA_len_box = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SA_len_box.sizePolicy().hasHeightForWidth())
        self.SA_len_box.setSizePolicy(sizePolicy)
        self.SA_len_box.setMinimumSize(QtCore.QSize(150, 0))
        self.SA_len_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.SA_len_box.setObjectName(_fromUtf8("SA_len_box"))
        self.horizontalLayout_54.addWidget(self.SA_len_box)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_50)
        self.gridLayout_3.addLayout(self.horizontalLayout_36, 0, 0, 1, 1)
        self.horizontalLayout_57 = QtGui.QHBoxLayout()
        self.horizontalLayout_57.setObjectName(_fromUtf8("horizontalLayout_57"))
        self.SA_read_b = QtGui.QPushButton(self.groupBox_7)
        self.SA_read_b.setObjectName(_fromUtf8("SA_read_b"))
        self.horizontalLayout_57.addWidget(self.SA_read_b)
        self.SA_set_b = QtGui.QPushButton(self.groupBox_7)
        self.SA_set_b.setObjectName(_fromUtf8("SA_set_b"))
        self.horizontalLayout_57.addWidget(self.SA_set_b)
        self.gridLayout_3.addLayout(self.horizontalLayout_57, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(90, 0))
        self.label_22.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_25.addWidget(self.label_22)
        self.S_ip_box = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S_ip_box.sizePolicy().hasHeightForWidth())
        self.S_ip_box.setSizePolicy(sizePolicy)
        self.S_ip_box.setMinimumSize(QtCore.QSize(150, 0))
        self.S_ip_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.S_ip_box.setText(_fromUtf8(""))
        self.S_ip_box.setObjectName(_fromUtf8("S_ip_box"))
        self.horizontalLayout_25.addWidget(self.S_ip_box)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(90, 0))
        self.label_23.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_26.addWidget(self.label_23)
        self.S_ip_port = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S_ip_port.sizePolicy().hasHeightForWidth())
        self.S_ip_port.setSizePolicy(sizePolicy)
        self.S_ip_port.setMinimumSize(QtCore.QSize(150, 0))
        self.S_ip_port.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.S_ip_port.setObjectName(_fromUtf8("S_ip_port"))
        self.horizontalLayout_26.addWidget(self.S_ip_port)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_27)
        self.gridLayout_2.addLayout(self.horizontalLayout_28, 0, 0, 1, 1)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.S_ip_read_b = QtGui.QPushButton(self.groupBox_3)
        self.S_ip_read_b.setObjectName(_fromUtf8("S_ip_read_b"))
        self.horizontalLayout_39.addWidget(self.S_ip_read_b)
        self.S_ip_set_b = QtGui.QPushButton(self.groupBox_3)
        self.S_ip_set_b.setObjectName(_fromUtf8("S_ip_set_b"))
        self.horizontalLayout_39.addWidget(self.S_ip_set_b)
        self.gridLayout_2.addLayout(self.horizontalLayout_39, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_24 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(90, 0))
        self.label_24.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_30.addWidget(self.label_24)
        self.local_IP_mode_l = QtGui.QComboBox(self.groupBox_4)
        self.local_IP_mode_l.setObjectName(_fromUtf8("local_IP_mode_l"))
        self.local_IP_mode_l.addItem(_fromUtf8(""))
        self.local_IP_mode_l.addItem(_fromUtf8(""))
        self.local_IP_mode_l.addItem(_fromUtf8(""))
        self.horizontalLayout_30.addWidget(self.local_IP_mode_l)
        self.verticalLayout_6.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_28 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(90, 0))
        self.label_28.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_34.addWidget(self.label_28)
        self.local_IP_box = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_IP_box.sizePolicy().hasHeightForWidth())
        self.local_IP_box.setSizePolicy(sizePolicy)
        self.local_IP_box.setMinimumSize(QtCore.QSize(150, 0))
        self.local_IP_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.local_IP_box.setObjectName(_fromUtf8("local_IP_box"))
        self.horizontalLayout_34.addWidget(self.local_IP_box)
        self.verticalLayout_6.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_29 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(90, 0))
        self.label_29.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_35.addWidget(self.label_29)
        self.local_mask_box = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_mask_box.sizePolicy().hasHeightForWidth())
        self.local_mask_box.setSizePolicy(sizePolicy)
        self.local_mask_box.setMinimumSize(QtCore.QSize(150, 0))
        self.local_mask_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.local_mask_box.setObjectName(_fromUtf8("local_mask_box"))
        self.horizontalLayout_35.addWidget(self.local_mask_box)
        self.verticalLayout_6.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_29.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_31 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(90, 0))
        self.label_31.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_37.addWidget(self.label_31)
        self.local_gate_addr_box = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_gate_addr_box.sizePolicy().hasHeightForWidth())
        self.local_gate_addr_box.setSizePolicy(sizePolicy)
        self.local_gate_addr_box.setMinimumSize(QtCore.QSize(150, 0))
        self.local_gate_addr_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.local_gate_addr_box.setObjectName(_fromUtf8("local_gate_addr_box"))
        self.horizontalLayout_37.addWidget(self.local_gate_addr_box)
        self.verticalLayout_7.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_32 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(90, 0))
        self.label_32.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_38.addWidget(self.label_32)
        self.ppp_usr_box = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppp_usr_box.sizePolicy().hasHeightForWidth())
        self.ppp_usr_box.setSizePolicy(sizePolicy)
        self.ppp_usr_box.setMinimumSize(QtCore.QSize(150, 0))
        self.ppp_usr_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.ppp_usr_box.setObjectName(_fromUtf8("ppp_usr_box"))
        self.horizontalLayout_38.addWidget(self.ppp_usr_box)
        self.verticalLayout_7.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_36 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMinimumSize(QtCore.QSize(90, 0))
        self.label_36.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_42.addWidget(self.label_36)
        self.ppp_pw_box = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppp_pw_box.sizePolicy().hasHeightForWidth())
        self.ppp_pw_box.setSizePolicy(sizePolicy)
        self.ppp_pw_box.setMinimumSize(QtCore.QSize(150, 0))
        self.ppp_pw_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.ppp_pw_box.setObjectName(_fromUtf8("ppp_pw_box"))
        self.horizontalLayout_42.addWidget(self.ppp_pw_box)
        self.verticalLayout_7.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_29.addLayout(self.verticalLayout_7)
        self.gridLayout_5.addLayout(self.horizontalLayout_29, 0, 0, 1, 1)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.local_read_b = QtGui.QPushButton(self.groupBox_4)
        self.local_read_b.setObjectName(_fromUtf8("local_read_b"))
        self.horizontalLayout_40.addWidget(self.local_read_b)
        self.locao_set_b = QtGui.QPushButton(self.groupBox_4)
        self.locao_set_b.setObjectName(_fromUtf8("locao_set_b"))
        self.horizontalLayout_40.addWidget(self.locao_set_b)
        self.gridLayout_5.addLayout(self.horizontalLayout_40, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 2, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 2, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.work_mode_l = QtGui.QComboBox(self.groupBox_2)
        self.work_mode_l.setObjectName(_fromUtf8("work_mode_l"))
        self.work_mode_l.addItem(_fromUtf8(""))
        self.work_mode_l.addItem(_fromUtf8(""))
        self.work_mode_l.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.work_mode_l)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(90, 0))
        self.label_3.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.online_mode_l = QtGui.QComboBox(self.groupBox_2)
        self.online_mode_l.setObjectName(_fromUtf8("online_mode_l"))
        self.online_mode_l.addItem(_fromUtf8(""))
        self.online_mode_l.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.online_mode_l)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(90, 0))
        self.label_7.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.connect_mode_l = QtGui.QComboBox(self.groupBox_2)
        self.connect_mode_l.setObjectName(_fromUtf8("connect_mode_l"))
        self.connect_mode_l.addItem(_fromUtf8(""))
        self.connect_mode_l.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.connect_mode_l)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(90, 0))
        self.label_8.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.connect_app_mode_l = QtGui.QComboBox(self.groupBox_2)
        self.connect_app_mode_l.setObjectName(_fromUtf8("connect_app_mode_l"))
        self.connect_app_mode_l.addItem(_fromUtf8(""))
        self.connect_app_mode_l.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.connect_app_mode_l)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(90, 0))
        self.label_4.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.listen_port_box = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listen_port_box.sizePolicy().hasHeightForWidth())
        self.listen_port_box.setSizePolicy(sizePolicy)
        self.listen_port_box.setMinimumSize(QtCore.QSize(150, 0))
        self.listen_port_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.listen_port_box.setObjectName(_fromUtf8("listen_port_box"))
        self.horizontalLayout_7.addWidget(self.listen_port_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(90, 0))
        self.label_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.APN_box = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.APN_box.sizePolicy().hasHeightForWidth())
        self.APN_box.setSizePolicy(sizePolicy)
        self.APN_box.setMinimumSize(QtCore.QSize(150, 0))
        self.APN_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.APN_box.setObjectName(_fromUtf8("APN_box"))
        self.horizontalLayout_8.addWidget(self.APN_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(90, 0))
        self.label_6.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.usr_box = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usr_box.sizePolicy().hasHeightForWidth())
        self.usr_box.setSizePolicy(sizePolicy)
        self.usr_box.setMinimumSize(QtCore.QSize(150, 0))
        self.usr_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.usr_box.setObjectName(_fromUtf8("usr_box"))
        self.horizontalLayout_9.addWidget(self.usr_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_24.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(90, 0))
        self.label_9.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.pw_box = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pw_box.sizePolicy().hasHeightForWidth())
        self.pw_box.setSizePolicy(sizePolicy)
        self.pw_box.setMinimumSize(QtCore.QSize(150, 0))
        self.pw_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.pw_box.setObjectName(_fromUtf8("pw_box"))
        self.horizontalLayout_11.addWidget(self.pw_box)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(90, 0))
        self.label_10.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.proxy_addr_box = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxy_addr_box.sizePolicy().hasHeightForWidth())
        self.proxy_addr_box.setSizePolicy(sizePolicy)
        self.proxy_addr_box.setMinimumSize(QtCore.QSize(150, 0))
        self.proxy_addr_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.proxy_addr_box.setObjectName(_fromUtf8("proxy_addr_box"))
        self.horizontalLayout_12.addWidget(self.proxy_addr_box)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(90, 0))
        self.label_11.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_13.addWidget(self.label_11)
        self.proxy_prot_box = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxy_prot_box.sizePolicy().hasHeightForWidth())
        self.proxy_prot_box.setSizePolicy(sizePolicy)
        self.proxy_prot_box.setMinimumSize(QtCore.QSize(150, 0))
        self.proxy_prot_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.proxy_prot_box.setObjectName(_fromUtf8("proxy_prot_box"))
        self.horizontalLayout_13.addWidget(self.proxy_prot_box)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(90, 0))
        self.label_12.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_14.addWidget(self.label_12)
        self.over_tm_box = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.over_tm_box.sizePolicy().hasHeightForWidth())
        self.over_tm_box.setSizePolicy(sizePolicy)
        self.over_tm_box.setMinimumSize(QtCore.QSize(150, 0))
        self.over_tm_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.over_tm_box.setObjectName(_fromUtf8("over_tm_box"))
        self.horizontalLayout_14.addWidget(self.over_tm_box)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(90, 0))
        self.label_13.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.retry_box = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.retry_box.sizePolicy().hasHeightForWidth())
        self.retry_box.setSizePolicy(sizePolicy)
        self.retry_box.setMinimumSize(QtCore.QSize(150, 0))
        self.retry_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.retry_box.setObjectName(_fromUtf8("retry_box"))
        self.horizontalLayout_15.addWidget(self.retry_box)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(90, 0))
        self.label_14.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_16.addWidget(self.label_14)
        self.heart_tm_box = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heart_tm_box.sizePolicy().hasHeightForWidth())
        self.heart_tm_box.setSizePolicy(sizePolicy)
        self.heart_tm_box.setMinimumSize(QtCore.QSize(150, 0))
        self.heart_tm_box.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.heart_tm_box.setObjectName(_fromUtf8("heart_tm_box"))
        self.horizontalLayout_16.addWidget(self.heart_tm_box)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_24.addLayout(self.verticalLayout_4)
        self.gridLayout_4.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.commu_read_b = QtGui.QPushButton(self.groupBox_2)
        self.commu_read_b.setObjectName(_fromUtf8("commu_read_b"))
        self.horizontalLayout_41.addWidget(self.commu_read_b)
        self.commu_set_b = QtGui.QPushButton(self.groupBox_2)
        self.commu_set_b.setObjectName(_fromUtf8("commu_set_b"))
        self.horizontalLayout_41.addWidget(self.commu_set_b)
        self.gridLayout_4.addLayout(self.horizontalLayout_41, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 3, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem7, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.esam_info_read_b = QtGui.QPushButton(self.tab_3)
        self.esam_info_read_b.setObjectName(_fromUtf8("esam_info_read_b"))
        self.verticalLayout_11.addWidget(self.esam_info_read_b)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_26 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(110, 0))
        self.label_26.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_31.addWidget(self.label_26)
        self.esam_no_box = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_no_box.sizePolicy().hasHeightForWidth())
        self.esam_no_box.setSizePolicy(sizePolicy)
        self.esam_no_box.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_no_box.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_no_box.setBaseSize(QtCore.QSize(150, 0))
        self.esam_no_box.setObjectName(_fromUtf8("esam_no_box"))
        self.horizontalLayout_31.addWidget(self.esam_no_box)
        self.verticalLayout_12.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.label_27 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(110, 0))
        self.label_27.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_43.addWidget(self.label_27)
        self.esam_ver_box = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_ver_box.sizePolicy().hasHeightForWidth())
        self.esam_ver_box.setSizePolicy(sizePolicy)
        self.esam_ver_box.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_ver_box.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_ver_box.setBaseSize(QtCore.QSize(150, 0))
        self.esam_ver_box.setObjectName(_fromUtf8("esam_ver_box"))
        self.horizontalLayout_43.addWidget(self.esam_ver_box)
        self.verticalLayout_12.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.label_30 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(110, 0))
        self.label_30.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_44.addWidget(self.label_30)
        self.key_ver_box = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key_ver_box.sizePolicy().hasHeightForWidth())
        self.key_ver_box.setSizePolicy(sizePolicy)
        self.key_ver_box.setMinimumSize(QtCore.QSize(100, 0))
        self.key_ver_box.setSizeIncrement(QtCore.QSize(150, 0))
        self.key_ver_box.setBaseSize(QtCore.QSize(150, 0))
        self.key_ver_box.setObjectName(_fromUtf8("key_ver_box"))
        self.horizontalLayout_44.addWidget(self.key_ver_box)
        self.verticalLayout_12.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_33 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setMinimumSize(QtCore.QSize(110, 0))
        self.label_33.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_45.addWidget(self.label_33)
        self.dialog_tm_box = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_tm_box.sizePolicy().hasHeightForWidth())
        self.dialog_tm_box.setSizePolicy(sizePolicy)
        self.dialog_tm_box.setMinimumSize(QtCore.QSize(100, 0))
        self.dialog_tm_box.setSizeIncrement(QtCore.QSize(150, 0))
        self.dialog_tm_box.setBaseSize(QtCore.QSize(150, 0))
        self.dialog_tm_box.setObjectName(_fromUtf8("dialog_tm_box"))
        self.horizontalLayout_45.addWidget(self.dialog_tm_box)
        self.verticalLayout_12.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.label_34 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setMinimumSize(QtCore.QSize(110, 0))
        self.label_34.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_46.addWidget(self.label_34)
        self.dialog_remain_box = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_remain_box.sizePolicy().hasHeightForWidth())
        self.dialog_remain_box.setSizePolicy(sizePolicy)
        self.dialog_remain_box.setMinimumSize(QtCore.QSize(100, 0))
        self.dialog_remain_box.setSizeIncrement(QtCore.QSize(150, 0))
        self.dialog_remain_box.setBaseSize(QtCore.QSize(150, 0))
        self.dialog_remain_box.setObjectName(_fromUtf8("dialog_remain_box"))
        self.horizontalLayout_46.addWidget(self.dialog_remain_box)
        self.verticalLayout_12.addLayout(self.horizontalLayout_46)
        spacerItem8 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem8)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.label_35 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setMinimumSize(QtCore.QSize(110, 0))
        self.label_35.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_47.addWidget(self.label_35)
        self.addr_counter_box = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addr_counter_box.sizePolicy().hasHeightForWidth())
        self.addr_counter_box.setSizePolicy(sizePolicy)
        self.addr_counter_box.setMinimumSize(QtCore.QSize(100, 0))
        self.addr_counter_box.setSizeIncrement(QtCore.QSize(150, 0))
        self.addr_counter_box.setBaseSize(QtCore.QSize(150, 0))
        self.addr_counter_box.setObjectName(_fromUtf8("addr_counter_box"))
        self.horizontalLayout_47.addWidget(self.addr_counter_box)
        self.verticalLayout_9.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_52 = QtGui.QHBoxLayout()
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.label_41 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setMinimumSize(QtCore.QSize(110, 0))
        self.label_41.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_52.addWidget(self.label_41)
        self.rpt_counter_box = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rpt_counter_box.sizePolicy().hasHeightForWidth())
        self.rpt_counter_box.setSizePolicy(sizePolicy)
        self.rpt_counter_box.setMinimumSize(QtCore.QSize(100, 0))
        self.rpt_counter_box.setSizeIncrement(QtCore.QSize(150, 0))
        self.rpt_counter_box.setBaseSize(QtCore.QSize(150, 0))
        self.rpt_counter_box.setObjectName(_fromUtf8("rpt_counter_box"))
        self.horizontalLayout_52.addWidget(self.rpt_counter_box)
        self.verticalLayout_9.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtGui.QHBoxLayout()
        self.horizontalLayout_53.setObjectName(_fromUtf8("horizontalLayout_53"))
        self.label_42 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setMinimumSize(QtCore.QSize(110, 0))
        self.label_42.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_53.addWidget(self.label_42)
        self.app_radio_box = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_radio_box.sizePolicy().hasHeightForWidth())
        self.app_radio_box.setSizePolicy(sizePolicy)
        self.app_radio_box.setMinimumSize(QtCore.QSize(100, 0))
        self.app_radio_box.setSizeIncrement(QtCore.QSize(150, 0))
        self.app_radio_box.setBaseSize(QtCore.QSize(150, 0))
        self.app_radio_box.setObjectName(_fromUtf8("app_radio_box"))
        self.horizontalLayout_53.addWidget(self.app_radio_box)
        self.verticalLayout_9.addLayout(self.horizontalLayout_53)
        self.gridLayout_8.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_5)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        spacerItem9 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_13.addItem(spacerItem9)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_55 = QtGui.QHBoxLayout()
        self.horizontalLayout_55.setObjectName(_fromUtf8("horizontalLayout_55"))
        self.label_44 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMinimumSize(QtCore.QSize(110, 0))
        self.label_44.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_55.addWidget(self.label_44)
        self.terminal_ver_box = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal_ver_box.sizePolicy().hasHeightForWidth())
        self.terminal_ver_box.setSizePolicy(sizePolicy)
        self.terminal_ver_box.setMinimumSize(QtCore.QSize(100, 0))
        self.terminal_ver_box.setSizeIncrement(QtCore.QSize(150, 0))
        self.terminal_ver_box.setBaseSize(QtCore.QSize(150, 0))
        self.terminal_ver_box.setObjectName(_fromUtf8("terminal_ver_box"))
        self.horizontalLayout_55.addWidget(self.terminal_ver_box)
        self.verticalLayout_10.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_56 = QtGui.QHBoxLayout()
        self.horizontalLayout_56.setObjectName(_fromUtf8("horizontalLayout_56"))
        self.label_45 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setMinimumSize(QtCore.QSize(110, 0))
        self.label_45.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_56.addWidget(self.label_45)
        self.host_ver_box = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.host_ver_box.sizePolicy().hasHeightForWidth())
        self.host_ver_box.setSizePolicy(sizePolicy)
        self.host_ver_box.setMinimumSize(QtCore.QSize(100, 0))
        self.host_ver_box.setSizeIncrement(QtCore.QSize(150, 0))
        self.host_ver_box.setBaseSize(QtCore.QSize(150, 0))
        self.host_ver_box.setObjectName(_fromUtf8("host_ver_box"))
        self.horizontalLayout_56.addWidget(self.host_ver_box)
        self.verticalLayout_10.addLayout(self.horizontalLayout_56)
        self.verticalLayout_14.addLayout(self.verticalLayout_10)
        self.verticalLayout_13.addWidget(self.groupBox_6)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem10)
        self.verticalLayout_11.addLayout(self.verticalLayout_13)
        self.horizontalLayout_49.addLayout(self.verticalLayout_11)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.certi_l = QtGui.QComboBox(self.tab_3)
        self.certi_l.setObjectName(_fromUtf8("certi_l"))
        self.certi_l.addItem(_fromUtf8(""))
        self.certi_l.addItem(_fromUtf8(""))
        self.horizontalLayout_48.addWidget(self.certi_l)
        self.certi_read_b = QtGui.QPushButton(self.tab_3)
        self.certi_read_b.setObjectName(_fromUtf8("certi_read_b"))
        self.horizontalLayout_48.addWidget(self.certi_read_b)
        self.verticalLayout_15.addLayout(self.horizontalLayout_48)
        self.certi_box = QtGui.QPlainTextEdit(self.tab_3)
        self.certi_box.setObjectName(_fromUtf8("certi_box"))
        self.verticalLayout_15.addWidget(self.certi_box)
        self.horizontalLayout_49.addLayout(self.verticalLayout_15)
        self.gridLayout_9.addLayout(self.horizontalLayout_49, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget, 0, 0, 1, 1)
        ParamWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ParamWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ParamWindow)

    def retranslateUi(self, ParamWindow):
        ParamWindow.setWindowTitle(_translate("ParamWindow", "参数配置", None))
        self.groupBox.setTitle(_translate("ParamWindow", "对时", None))
        self.DT_read_b.setText(_translate("ParamWindow", "读取", None))
        self.DT_set_b.setText(_translate("ParamWindow", "设置", None))
        self.DT_set_now_b.setText(_translate("ParamWindow", "设置当前时间", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ParamWindow", "对时", None))
        self.groupBox_7.setTitle(_translate("ParamWindow", "通信地址", None))
        self.label_37.setText(_translate("ParamWindow", "地址", None))
        self.label_38.setText(_translate("ParamWindow", "长度", None))
        self.SA_read_b.setText(_translate("ParamWindow", "读取", None))
        self.SA_set_b.setText(_translate("ParamWindow", "设置", None))
        self.groupBox_3.setTitle(_translate("ParamWindow", "主站通信参数表", None))
        self.label_22.setText(_translate("ParamWindow", "IP地址", None))
        self.label_23.setText(_translate("ParamWindow", "端口", None))
        self.S_ip_read_b.setText(_translate("ParamWindow", "读取", None))
        self.S_ip_set_b.setText(_translate("ParamWindow", "设置", None))
        self.groupBox_4.setTitle(_translate("ParamWindow", "网络配置", None))
        self.label_24.setText(_translate("ParamWindow", "IP配置方式", None))
        self.local_IP_mode_l.setItemText(0, _translate("ParamWindow", "DHCP（0）", None))
        self.local_IP_mode_l.setItemText(1, _translate("ParamWindow", "静态（1）", None))
        self.local_IP_mode_l.setItemText(2, _translate("ParamWindow", "PPPoE（2）", None))
        self.label_28.setText(_translate("ParamWindow", "IP地址", None))
        self.label_29.setText(_translate("ParamWindow", "子网掩码", None))
        self.label_31.setText(_translate("ParamWindow", "网关地址", None))
        self.label_32.setText(_translate("ParamWindow", "PPPoE用户名", None))
        self.label_36.setText(_translate("ParamWindow", "PPPoE密码", None))
        self.local_read_b.setText(_translate("ParamWindow", "读取", None))
        self.locao_set_b.setText(_translate("ParamWindow", "设置", None))
        self.groupBox_2.setTitle(_translate("ParamWindow", "通信配置", None))
        self.label_2.setText(_translate("ParamWindow", "工作模式", None))
        self.work_mode_l.setItemText(0, _translate("ParamWindow", "混合模式（0）", None))
        self.work_mode_l.setItemText(1, _translate("ParamWindow", "客户机模式（1）", None))
        self.work_mode_l.setItemText(2, _translate("ParamWindow", "服务器模式（2）", None))
        self.label_3.setText(_translate("ParamWindow", "在线方式", None))
        self.online_mode_l.setItemText(0, _translate("ParamWindow", "永久在线（0）", None))
        self.online_mode_l.setItemText(1, _translate("ParamWindow", "被动激活（1）", None))
        self.label_7.setText(_translate("ParamWindow", "连接方式", None))
        self.connect_mode_l.setItemText(0, _translate("ParamWindow", "TCP（0）", None))
        self.connect_mode_l.setItemText(1, _translate("ParamWindow", "UDP（1）", None))
        self.label_8.setText(_translate("ParamWindow", "连接应用方式", None))
        self.connect_app_mode_l.setItemText(0, _translate("ParamWindow", "主备模式（0）", None))
        self.connect_app_mode_l.setItemText(1, _translate("ParamWindow", "多连接模式（1）", None))
        self.label_4.setText(_translate("ParamWindow", "侦听端口", None))
        self.label_5.setText(_translate("ParamWindow", "APN", None))
        self.label_6.setText(_translate("ParamWindow", "用户名", None))
        self.label_9.setText(_translate("ParamWindow", "密码", None))
        self.label_10.setText(_translate("ParamWindow", "代理服务器地址", None))
        self.label_11.setText(_translate("ParamWindow", "代理端口", None))
        self.label_12.setText(_translate("ParamWindow", "超时时间", None))
        self.label_13.setText(_translate("ParamWindow", "重发次数", None))
        self.label_14.setText(_translate("ParamWindow", "心跳周期", None))
        self.commu_read_b.setText(_translate("ParamWindow", "读取", None))
        self.commu_set_b.setText(_translate("ParamWindow", "设置", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ParamWindow", "通信参数", None))
        self.esam_info_read_b.setText(_translate("ParamWindow", "读取", None))
        self.label_26.setText(_translate("ParamWindow", "ESAM序列号", None))
        self.label_27.setText(_translate("ParamWindow", "ESAM版本号", None))
        self.label_30.setText(_translate("ParamWindow", "对称密钥版本", None))
        self.label_33.setText(_translate("ParamWindow", "会话时效门限", None))
        self.label_34.setText(_translate("ParamWindow", "会话时效剩余时间", None))
        self.groupBox_5.setTitle(_translate("ParamWindow", "当前计数器", None))
        self.label_35.setText(_translate("ParamWindow", "单地址应用协商计数器", None))
        self.label_41.setText(_translate("ParamWindow", "主动上报计数器", None))
        self.label_42.setText(_translate("ParamWindow", "应用广播通信序列号", None))
        self.groupBox_6.setTitle(_translate("ParamWindow", "证书版本", None))
        self.label_44.setText(_translate("ParamWindow", "终端证书版本", None))
        self.label_45.setText(_translate("ParamWindow", "主站证书版本", None))
        self.certi_l.setItemText(0, _translate("ParamWindow", "终端证书", None))
        self.certi_l.setItemText(1, _translate("ParamWindow", "主站证书", None))
        self.certi_read_b.setText(_translate("ParamWindow", "读取", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ParamWindow", "ESAM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ParamWindow", "其他", None))

import icon_rc
