# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SerialWindow(object):
    def setupUi(self, SerialWindow):
        SerialWindow.setObjectName(_fromUtf8("SerialWindow"))
        SerialWindow.setWindowModality(QtCore.Qt.NonModal)
        SerialWindow.resize(848, 658)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Active, QtGui.QIcon.On)
        SerialWindow.setWindowIcon(icon)
        SerialWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        SerialWindow.setAnimated(True)
        SerialWindow.setTabShape(QtGui.QTabWidget.Rounded)
        SerialWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(SerialWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, 3, 1, 3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(5, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(9, 5, 9, 9)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.SA_type_list = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.SA_type_list.sizePolicy().hasHeightForWidth())
        self.SA_type_list.setSizePolicy(sizePolicy)
        self.SA_type_list.setObjectName(_fromUtf8("SA_type_list"))
        self.SA_type_list.addItem(_fromUtf8(""))
        self.SA_type_list.addItem(_fromUtf8(""))
        self.SA_type_list.addItem(_fromUtf8(""))
        self.SA_type_list.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.SA_type_list)
        self.SA_box = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.SA_box.sizePolicy().hasHeightForWidth())
        self.SA_box.setSizePolicy(sizePolicy)
        self.SA_box.setObjectName(_fromUtf8("SA_box"))
        self.horizontalLayout.addWidget(self.SA_box)
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.SA_len_box = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.SA_len_box.sizePolicy().hasHeightForWidth())
        self.SA_len_box.setSizePolicy(sizePolicy)
        self.SA_len_box.setObjectName(_fromUtf8("SA_len_box"))
        self.horizontalLayout.addWidget(self.SA_len_box)
        self.read_SA_b = QtGui.QPushButton(self.groupBox)
        self.read_SA_b.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.read_SA_b.sizePolicy().hasHeightForWidth())
        self.read_SA_b.setSizePolicy(sizePolicy)
        self.read_SA_b.setObjectName(_fromUtf8("read_SA_b"))
        self.horizontalLayout.addWidget(self.read_SA_b)
        self.horizontalLayout_5.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.com_list = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.com_list.sizePolicy().hasHeightForWidth())
        self.com_list.setSizePolicy(sizePolicy)
        self.com_list.setObjectName(_fromUtf8("com_list"))
        self.horizontalLayout_6.addWidget(self.com_list)
        self.link_b = QtGui.QPushButton(self.tab)
        self.link_b.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.link_b.sizePolicy().hasHeightForWidth())
        self.link_b.setSizePolicy(sizePolicy)
        self.link_b.setObjectName(_fromUtf8("link_b"))
        self.horizontalLayout_6.addWidget(self.link_b)
        self.unlink_b = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.unlink_b.sizePolicy().hasHeightForWidth())
        self.unlink_b.setSizePolicy(sizePolicy)
        self.unlink_b.setObjectName(_fromUtf8("unlink_b"))
        self.horizontalLayout_6.addWidget(self.unlink_b)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.port_box = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.port_box.sizePolicy().hasHeightForWidth())
        self.port_box.setSizePolicy(sizePolicy)
        self.port_box.setObjectName(_fromUtf8("port_box"))
        self.horizontalLayout_7.addWidget(self.port_box)
        self.start_b = QtGui.QPushButton(self.tab_2)
        self.start_b.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.start_b.sizePolicy().hasHeightForWidth())
        self.start_b.setSizePolicy(sizePolicy)
        self.start_b.setObjectName(_fromUtf8("start_b"))
        self.horizontalLayout_7.addWidget(self.start_b)
        self.stop_b = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stop_b.sizePolicy().hasHeightForWidth())
        self.stop_b.setSizePolicy(sizePolicy)
        self.stop_b.setObjectName(_fromUtf8("stop_b"))
        self.horizontalLayout_7.addWidget(self.stop_b)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tabWidget)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.translate_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.translate_button.sizePolicy().hasHeightForWidth())
        self.translate_button.setSizePolicy(sizePolicy)
        self.translate_button.setObjectName(_fromUtf8("translate_button"))
        self.horizontalLayout_3.addWidget(self.translate_button)
        self.send_clear_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.send_clear_button.sizePolicy().hasHeightForWidth())
        self.send_clear_button.setSizePolicy(sizePolicy)
        self.send_clear_button.setObjectName(_fromUtf8("send_clear_button"))
        self.horizontalLayout_3.addWidget(self.send_clear_button)
        self.quick_fix_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.quick_fix_button.sizePolicy().hasHeightForWidth())
        self.quick_fix_button.setSizePolicy(sizePolicy)
        self.quick_fix_button.setObjectName(_fromUtf8("quick_fix_button"))
        self.horizontalLayout_3.addWidget(self.quick_fix_button)
        self.send_button = QtGui.QPushButton(self.centralwidget)
        self.send_button.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.send_button.sizePolicy().hasHeightForWidth())
        self.send_button.setSizePolicy(sizePolicy)
        self.send_button.setObjectName(_fromUtf8("send_button"))
        self.horizontalLayout_3.addWidget(self.send_button)
        spacerItem4 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.receive_clear_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.receive_clear_button.sizePolicy().hasHeightForWidth())
        self.receive_clear_button.setSizePolicy(sizePolicy)
        self.receive_clear_button.setMouseTracking(False)
        self.receive_clear_button.setAcceptDrops(False)
        self.receive_clear_button.setAutoDefault(False)
        self.receive_clear_button.setDefault(False)
        self.receive_clear_button.setFlat(False)
        self.receive_clear_button.setObjectName(_fromUtf8("receive_clear_button"))
        self.horizontalLayout_3.addWidget(self.receive_clear_button)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.splitter_3 = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setHandleWidth(3)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.splitter = QtGui.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(3)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.send_input_box = QtGui.QTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.send_input_box.sizePolicy().hasHeightForWidth())
        self.send_input_box.setSizePolicy(sizePolicy)
        self.send_input_box.setAcceptDrops(False)
        self.send_input_box.setToolTip(_fromUtf8(""))
        self.send_input_box.setStatusTip(_fromUtf8(""))
        self.send_input_box.setWhatsThis(_fromUtf8(""))
        self.send_input_box.setAccessibleName(_fromUtf8(""))
        self.send_input_box.setAccessibleDescription(_fromUtf8(""))
        self.send_input_box.setAutoFillBackground(False)
        self.send_input_box.setStyleSheet(_fromUtf8(""))
        self.send_input_box.setFrameShape(QtGui.QFrame.NoFrame)
        self.send_input_box.setFrameShadow(QtGui.QFrame.Sunken)
        self.send_input_box.setMidLineWidth(1)
        self.send_input_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.send_input_box.setDocumentTitle(_fromUtf8(""))
        self.send_input_box.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.send_input_box.setOverwriteMode(False)
        self.send_input_box.setAcceptRichText(True)
        self.send_input_box.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.send_input_box.setObjectName(_fromUtf8("send_input_box"))
        self.send_output_box = QtGui.QTextEdit(self.splitter)
        self.send_output_box.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.send_output_box.sizePolicy().hasHeightForWidth())
        self.send_output_box.setSizePolicy(sizePolicy)
        self.send_output_box.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.send_output_box.setAcceptDrops(False)
        self.send_output_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.send_output_box.setAutoFillBackground(False)
        self.send_output_box.setObjectName(_fromUtf8("send_output_box"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(3)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.receive_input_box = QtGui.QTextEdit(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.receive_input_box.sizePolicy().hasHeightForWidth())
        self.receive_input_box.setSizePolicy(sizePolicy)
        self.receive_input_box.setAcceptDrops(False)
        self.receive_input_box.setToolTip(_fromUtf8(""))
        self.receive_input_box.setStatusTip(_fromUtf8(""))
        self.receive_input_box.setWhatsThis(_fromUtf8(""))
        self.receive_input_box.setAccessibleName(_fromUtf8(""))
        self.receive_input_box.setAccessibleDescription(_fromUtf8(""))
        self.receive_input_box.setAutoFillBackground(False)
        self.receive_input_box.setStyleSheet(_fromUtf8(""))
        self.receive_input_box.setFrameShape(QtGui.QFrame.NoFrame)
        self.receive_input_box.setFrameShadow(QtGui.QFrame.Sunken)
        self.receive_input_box.setMidLineWidth(1)
        self.receive_input_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.receive_input_box.setDocumentTitle(_fromUtf8(""))
        self.receive_input_box.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.receive_input_box.setOverwriteMode(False)
        self.receive_input_box.setAcceptRichText(True)
        self.receive_input_box.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.receive_input_box.setObjectName(_fromUtf8("receive_input_box"))
        self.receive_output_box = QtGui.QTextEdit(self.splitter_2)
        self.receive_output_box.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.receive_output_box.sizePolicy().hasHeightForWidth())
        self.receive_output_box.setSizePolicy(sizePolicy)
        self.receive_output_box.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.receive_output_box.setAcceptDrops(False)
        self.receive_output_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.receive_output_box.setAutoFillBackground(False)
        self.receive_output_box.setObjectName(_fromUtf8("receive_output_box"))
        self.verticalLayout.addWidget(self.splitter_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.trans_mode_button = QtGui.QPushButton(self.centralwidget)
        self.trans_mode_button.setMinimumSize(QtCore.QSize(0, 1))
        self.trans_mode_button.setObjectName(_fromUtf8("trans_mode_button"))
        self.horizontalLayout_2.addWidget(self.trans_mode_button)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.auto_fix_cb = QtGui.QCheckBox(self.centralwidget)
        self.auto_fix_cb.setMinimumSize(QtCore.QSize(0, 1))
        self.auto_fix_cb.setObjectName(_fromUtf8("auto_fix_cb"))
        self.horizontalLayout_2.addWidget(self.auto_fix_cb)
        spacerItem7 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.auto_trans_cb = QtGui.QCheckBox(self.centralwidget)
        self.auto_trans_cb.setMinimumSize(QtCore.QSize(0, 1))
        self.auto_trans_cb.setChecked(True)
        self.auto_trans_cb.setObjectName(_fromUtf8("auto_trans_cb"))
        self.horizontalLayout_2.addWidget(self.auto_trans_cb)
        spacerItem8 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.show_level_cb = QtGui.QCheckBox(self.centralwidget)
        self.show_level_cb.setMinimumSize(QtCore.QSize(0, 1))
        self.show_level_cb.setChecked(True)
        self.show_level_cb.setObjectName(_fromUtf8("show_level_cb"))
        self.horizontalLayout_2.addWidget(self.show_level_cb)
        self.always_top_cb = QtGui.QCheckBox(self.centralwidget)
        self.always_top_cb.setMinimumSize(QtCore.QSize(0, 1))
        self.always_top_cb.setObjectName(_fromUtf8("always_top_cb"))
        self.horizontalLayout_2.addWidget(self.always_top_cb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.splitter_3.raise_()
        SerialWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SerialWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.menubar.setPalette(palette)
        self.menubar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        SerialWindow.setMenuBar(self.menubar)
        self.about = QtGui.QAction(SerialWindow)
        self.about.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.about.setObjectName(_fromUtf8("about"))
        self.config = QtGui.QAction(SerialWindow)
        self.config.setObjectName(_fromUtf8("config"))
        self.param = QtGui.QAction(SerialWindow)
        self.param.setObjectName(_fromUtf8("param"))
        self.menu.addAction(self.about)
        self.menu_2.addAction(self.config)
        self.menu_3.addAction(self.param)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(SerialWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.send_clear_button, QtCore.SIGNAL(_fromUtf8("clicked()")), self.send_output_box.clear)
        QtCore.QObject.connect(self.send_clear_button, QtCore.SIGNAL(_fromUtf8("clicked()")), self.send_input_box.clear)
        QtCore.QObject.connect(self.receive_clear_button, QtCore.SIGNAL(_fromUtf8("clicked()")), self.receive_input_box.clear)
        QtCore.QObject.connect(self.receive_clear_button, QtCore.SIGNAL(_fromUtf8("clicked()")), self.receive_output_box.clear)
        QtCore.QMetaObject.connectSlotsByName(SerialWindow)
        SerialWindow.setTabOrder(self.send_input_box, self.send_clear_button)
        SerialWindow.setTabOrder(self.send_clear_button, self.send_output_box)
        SerialWindow.setTabOrder(self.send_output_box, self.show_level_cb)
        SerialWindow.setTabOrder(self.show_level_cb, self.send_button)
        SerialWindow.setTabOrder(self.send_button, self.receive_clear_button)
        SerialWindow.setTabOrder(self.receive_clear_button, self.receive_input_box)
        SerialWindow.setTabOrder(self.receive_input_box, self.receive_output_box)
        SerialWindow.setTabOrder(self.receive_output_box, self.auto_trans_cb)
        SerialWindow.setTabOrder(self.auto_trans_cb, self.SA_box)
        SerialWindow.setTabOrder(self.SA_box, self.SA_len_box)

    def retranslateUi(self, SerialWindow):
        SerialWindow.setWindowTitle(_translate("SerialWindow", "698解析工具（后台模式）_V4.0(2017.01)", None))
        self.groupBox.setTitle(_translate("SerialWindow", "通讯地址", None))
        self.label_2.setText(_translate("SerialWindow", "服务器", None))
        self.SA_type_list.setItemText(0, _translate("SerialWindow", "单地址", None))
        self.SA_type_list.setItemText(1, _translate("SerialWindow", "通配地址", None))
        self.SA_type_list.setItemText(2, _translate("SerialWindow", "组地址", None))
        self.SA_type_list.setItemText(3, _translate("SerialWindow", "广播地址", None))
        self.SA_box.setText(_translate("SerialWindow", "000000000001", None))
        self.label_3.setText(_translate("SerialWindow", "长度", None))
        self.SA_len_box.setText(_translate("SerialWindow", "6", None))
        self.read_SA_b.setText(_translate("SerialWindow", "读取", None))
        self.label.setText(_translate("SerialWindow", "连接", None))
        self.link_b.setText(_translate("SerialWindow", "连接", None))
        self.unlink_b.setText(_translate("SerialWindow", "刷新", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SerialWindow", "客户机模式", None))
        self.label_4.setText(_translate("SerialWindow", "端口", None))
        self.start_b.setText(_translate("SerialWindow", "启动", None))
        self.stop_b.setText(_translate("SerialWindow", "停止", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SerialWindow", "服务器模式", None))
        self.translate_button.setText(_translate("SerialWindow", "解析", None))
        self.send_clear_button.setText(_translate("SerialWindow", "清空", None))
        self.quick_fix_button.setText(_translate("SerialWindow", "修正格式", None))
        self.send_button.setText(_translate("SerialWindow", "请建立连接", None))
        self.receive_clear_button.setText(_translate("SerialWindow", "清空", None))
        self.send_input_box.setHtml(_translate("SerialWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.send_output_box.setHtml(_translate("SerialWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">说明：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.可连接串口或前置机，具体参数可在“设置”菜单中修改。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.“应用”按钮可将设置的地址应用到报文。勾选“自动修正”将在报文解析成功后自动修正报文中的地址和校验码。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.在输入框内输入APDU片段，软件将根据上方地址信息框中的信息自动添加链路层报文。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4.取消勾选下方“自动解析”将看到“解析”按钮。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5.“清空”按钮括号中显示的是输入框内报文的总长度。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">6.勾选下方“显示层级结构”可启用SEQUENCE、array、structure类型的缩进显示。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">7.“修正格式”可将报文格式化。当报文地址、长度或校验出错时，按此按钮可修改这些错误。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">8.本软件为终端开发部内部测试软件。在软件使用过程中遇到任何问题，请向665593反馈，谢谢。</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">9.Copyrigth(C), 2005-2020,Sanxing Medical &amp; Electric Co.,Ltd.</p></body></html>", None))
        self.receive_input_box.setHtml(_translate("SerialWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.receive_output_box.setHtml(_translate("SerialWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.trans_mode_button.setText(_translate("SerialWindow", "解析模式", None))
        self.auto_fix_cb.setText(_translate("SerialWindow", "自动修正", None))
        self.auto_trans_cb.setText(_translate("SerialWindow", "自动解析", None))
        self.show_level_cb.setText(_translate("SerialWindow", "显示层级结构", None))
        self.always_top_cb.setText(_translate("SerialWindow", "窗口置顶", None))
        self.menu.setTitle(_translate("SerialWindow", "帮助", None))
        self.menu_2.setTitle(_translate("SerialWindow", "设置", None))
        self.menu_3.setTitle(_translate("SerialWindow", "常用命令", None))
        self.about.setText(_translate("SerialWindow", "关于", None))
        self.config.setText(_translate("SerialWindow", "通信配置", None))
        self.param.setText(_translate("SerialWindow", "参数配置", None))

import icon_rc
